[package]
name = "screen_test"
version = "0.1.0"
authors = ["pi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11.3"
enum-repr = "0.2.4"
png = "0.15.0"
rgb = "0.8.14"
